export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const RELOAD_USER = 'RELOAD_USER'
export const RELOAD_USER_SUCCESS = 'RELOAD_USER_SUCCESS'

export const SHOPS_LOAD_REQUESTED = 'SHOPS_LOAD_REQUESTED'
export const SHOPS_LOAD_SUCCESS = 'SHOPS_LOAD_SUCCESS'
export const SHOPS_LOAD_FAIL = 'SHOPS_LOAD_FAIL'

export const CURRENT_SHOP_REQUESTED = 'CURRENT_SHOP_REQUESTED'
export const CURRENT_SHOP_SUCCESS = 'CURRENT_SHOP_SUCCESS'
export const CURRENT_SHOP_FAIL = 'CURRENT_SHOP_FAIL'

export const SHOP_ADD_REQUESTED = 'SHOP_ADD_REQUESTED'
export const SHOP_ADD_SUCCESS = 'SHOP_ADD_SUCCESS'
export const SHOP_ADD_FAIL = 'SHOP_ADD_FAIL'

// CUSTOMERS
export const CUSTOMERS_GET_REQUESTED = 'CUSTOMERS_GET_REQUESTED'
export const CUSTOMERS_GET_SUCCESS = 'CUSTOMERS_GET_SUCCESS'
export const CUSTOMERS_GET_FAIL = 'CUSTOMERS_GET_FAIL'

export const CUSTOMER_CREATE_REQUESTED = 'CUSTOMER_CREATE_REQUESTED'
export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS'
export const CUSTOMER_CREATE_FAIL = 'CUSTOMER_CREATE_FAIL'

export const CUSTOMER_GET_REQUESTED = 'CUSTOMER_GET_REQUESTED'
export const CUSTOMER_GET_SUCCESS = 'CUSTOMER_GET_SUCCESS'
export const CUSTOMER_GET_FAIL = 'CUSTOMER_GET_FAIL'

export const CUSTOMER_UPDATE_REQUESTED = 'CUSTOMER_UPDATE_REQUESTED'
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS'
export const CUSTOMER_UPDATE_FAIL = 'CUSTOMER_UPDATE_FAIL'

export const CUSTOMER_DELETE_REQUESTED = 'CUSTOMER_DELETE_REQUESTED'
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS'
export const CUSTOMER_DELETE_FAIL = 'CUSTOMER_DELETE_FAIL'

